
project_id = "htypnghgkpqiuhauslmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.claude-recommendations]
verify_jwt = false
import_map = "functions/claude-recommendations/import_map.json"

[functions.gemini-recommendations]
verify_jwt = false
import_map = "functions/gemini-recommendations/import_map.json"

[functions.get-mapbox-token]
verify_jwt = false
import_map = "functions/get-mapbox-token/import_map.json"

[functions.process-routes]
verify_jwt = false
import_map = "functions/process-routes/import_map.json"

[functions.realtime-sessions]
verify_jwt = false
import_map = "functions/realtime-sessions/import_map.json"

[functions.agent-triage]
verify_jwt = false

[functions.agent-search]
verify_jwt = false

[functions.agent-knowledge]
verify_jwt = false

[functions.agent-account]
verify_jwt = false

