
project_id = "htypnghgkpqiuhauslmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.trip-recommendations]
verify_jwt = false
import_map = "import_map.json"
