
project_id = "htypnghgkpqiuhauslmn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.trip-recommendations]
verify_jwt = false
import_map = "functions/trip-recommendations/import_map.json"

[functions.get-mapbox-token]
verify_jwt = false
import_map = "functions/get-mapbox-token/import_map.json"
