// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htypnghgkpqiuhauslmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eXBuZ2hna3BxaXVoYXVzbG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzY0OTcsImV4cCI6MjA1ODQxMjQ5N30.ESwOnBBHp2gx4bpp_3K7bg7gCHVzhHbpnsXi4Hg0H4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);